Pagination of products
braimor/ecommerce pull request #8
Opened 2021-08-03 19:34 UTC by brimorales

Pagination of products with Pagy tool.

![Captura de Pantalla 2021-08-03 a la(s) 16 32 44](https://user-images.githubusercontent.com/83039278/128075087-cb135fd2-eced-4ec1-be70-be66b6b89011.png)

![Captura de Pantalla 2021-08-03 a la(s) 16 33 36](https://user-images.githubusercontent.com/83039278/128075194-392d7843-7064-455e-bd64-9fbd9ac49e7e.png)

2021-08-03 21:20 UTC, diebas commented on app/assets/images/bag.html
> +<!DOCTYPE html>
Is this html necessary? I think it will be better to use an image file instead of an html.

2021-08-03 21:20 UTC, diebas commented on app/assets/stylesheets/product.scss
> +// Place all the styles related to the Product controller here.
remove this kind of files if you are not using them

2021-08-03 21:20 UTC, diebas commented on app/controllers/products_controller.rb
> +    def show
take care of indentation

2021-08-03 21:20 UTC, diebas commented on app/views/products/index.html.erb
> +
too many blank lines at the end of the file

2021-08-03 21:20 UTC, diebas commented on test/controllers/products_controller_test.rb
> +require "test_helper"
remove unused file

2021-08-03 21:20 UTC, diebas commented on app/views/products/index.json.jbuilder
> +json.array! @products, partial: "products/product", as: :product
what are you using this jbuilder for?

2021-08-05 18:52 UTC, aperezcristina requested changes

2021-08-05 18:52 UTC, aperezcristina commented on app/views/products/index.html.erb
> +</div>
```suggestion
</div>

```

2021-08-05 18:52 UTC, aperezcristina commented on app/views/products/index.html.erb
> +</div>
Leave a empty line at the end of files

2021-08-17 18:22 UTC, diebas approved these changes

2021-08-17 20:02 UTC, merged